version: 2
jobs:
  build:
    machine: True
    steps:
      - run:
          name: dependencies
          command: sudo apt update 
      - run:
          name: dependencies
          command: sudo apt install transmission-cli ffmpeg git python3 
