version: 2
jobs:
  build:
    machine: True
    steps:
      - run:
          name: getting script
          command: wget https://raw.githubusercontent.com/revanthstrakz/script/master/circle_m31.bash
